### ISSUE TITLE
Promising library, but the examples are inscrutable

### ISSUE THREAD

**Issue by fwextensions** [STRML/react-grid-layout#135]
I spent about an hour trying to get some of the examples working in my own environment, but none of them worked correctly.  It seems like there's a lot of magic going on with WebPack, so it's not clear what code is being included and from where when just looking at the example pages.  

It would help a lot to have some simple example pages that include all the CSS and JS files through explicit tags, rather than a build process.  I eventually stumbled upon the `simple-include.html` file, but that doesn't appear to work anymore.  

All I'm trying to do is get a single-row of rearrangeable items of identical size.  Seems like it should be easy to do, but I never got any of the library's snapping or rearranging behaviors to actually work.

**Comment by STRML** [comment]
`npm install; npm run build-example`.

**Comment by fwextensions** [comment]
That just builds the example bundles, which I've inspected from the demo pages hosted on github.io.  But I haven't found anyway to see what is actually instantiating the components on the various demo pages.  And for some reason, the JS files, like `1-basic.bundle.js`, that are loaded on the HTML page, aren't visible in Chrome devtools. 

For instance, the basic example exports the BasicLayout component.  What adds that to the page?  What specifies its `onLayoutChange` handler in props? 

	  onLayoutChange: function onLayoutChange(layout) {
	    this.props.onLayoutChange(layout);
	  },

Looking at `common.js` file, I see an ExampleLayout component that sets the layout state to new changed layout:

	    onLayoutChange: function onLayoutChange(layout) {
	      this.setState({ layout: layout });
	    },

Maybe without that, dragged elements don't snap into the grid?  It's hard to know.

**Comment by mosse** [comment]
Took me a little bit to untangle, but it's all there :)

`/test/test-hook.jsx/` instantiates each example (as specified in `/test/dev-hook.jsx/`) and sets `onLayoutChange`.

Hope that serves as a useful pointer.

**Comment by NoahMarconi** [comment]
npm run build-example is not working on my end. Any idea what's causing this? 

I'm on Windows 7 if that makes a difference.

```{sh}
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\noah.marconi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-example' ]
2 info using npm@3.3.9
3 info using node@v4.2.1
4 verbose run-script [ 'prebuild-example', 'build-example', 'postbuild-example' ]
5 info lifecycle react-grid-layout@0.10.0-beta1~prebuild-example: react-grid-layout@0.10.0-beta1
6 silly lifecycle react-grid-layout@0.10.0-beta1~prebuild-example: no script for prebuild-example, continuing
7 info lifecycle react-grid-layout@0.10.0-beta1~build-example: react-grid-layout@0.10.0-beta1
8 verbose lifecycle react-grid-layout@0.10.0-beta1~build-example: unsafe-perm in lifecycle true
9 verbose lifecycle react-grid-layout@0.10.0-beta1~build-example: PATH: C:\Users\noah.marconi\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\noah.marconi\Desktop\react-grid-layout-next\node_modules\.bin;C:\Program Files\ConEmu\ConEmu;C:\Ruby21-x64\bin;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Riverbed\Steelhead Mobile\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\GitExtensions\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\noah.marconi\AppData\Local\atom\bin;C:\Program Files\ConEmu;C:\Users\noah.marconi\AppData\Local\Pandoc\;C:\Program Files\phantomjs\bin;C:\Users\noah.marconi\AppData\Roaming\npm;C:\Python27
10 verbose lifecycle react-grid-layout@0.10.0-beta1~build-example: CWD: C:\Users\noah.marconi\Desktop\react-grid-layout-next
11 silly lifecycle react-grid-layout@0.10.0-beta1~build-example: Args: [ '/d /s /c',
11 silly lifecycle   'webpack --config webpack-examples.config.js; node ./examples/generate.js' ]
12 silly lifecycle react-grid-layout@0.10.0-beta1~build-example: Returned: code: 1  signal: null
13 info lifecycle react-grid-layout@0.10.0-beta1~build-example: Failed to exec build-example script
14 verbose stack Error: react-grid-layout@0.10.0-beta1 build-example: `webpack --config webpack-examples.config.js; node ./examples/generate.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\noah.marconi\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\noah.marconi\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-grid-layout@0.10.0-beta1
16 verbose cwd C:\Users\noah.marconi\Desktop\react-grid-layout-next
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\noah.marconi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-example"
19 error node v4.2.1
20 error npm  v3.3.9
21 error code ELIFECYCLE
22 error react-grid-layout@0.10.0-beta1 build-example: `webpack --config webpack-examples.config.js; node ./examples/generate.js`
22 error Exit status 1
23 error Failed at the react-grid-layout@0.10.0-beta1 build-example script 'webpack --config webpack-examples.config.js; node ./examples/generate.js'.
23 error This is most likely a problem with the react-grid-layout package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack-examples.config.js; node ./examples/generate.js
23 error You can get their info via:
23 error     npm owner ls react-grid-layout
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jjarmain** [comment]
The examples are not very intuitive at first, it would be awesome if a gitter channel could be setup for the community.

**Comment by STRML** [comment]
Almost certainly a Windows issue - sorry, I don't support Windows in the build process, but would be happy to take a PR for it if you get it working.

**Comment by NoahMarconi** [comment]
In case it comes up for others, using cygwin on windows should solve the problem from my prev comment.
