### ISSUE TITLE
Npm install fails from cloned repo (within an existing project)

### ISSUE THREAD

**Issue by chadobado** [STRML/react-grid-layout#51]
Update:  I've noticed the following happens only when required as a module in an existing project.

Noticed the NPM is out of date (does not include ```verticalCompact```), so attempted to build from the repo itself...

```
> precommit-hook@2.0.1 install /Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook
> node bin/install

/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:138
	throw new Error('Unable to find a .git folder for this project');
	      ^
Error: Unable to find a .git folder for this project
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:138:8)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
    at Object.exports.findGitRoot (/Users/Chad/react-grid-test/node_modules/react-grid-layout/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:135:24)
npm http 304 https://registry.npmjs.org/stable
npm ERR! precommit-hook@2.0.1 install: `node bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the precommit-hook@2.0.1 install script.
npm ERR! This is most likely a problem with the precommit-hook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls precommit-hook
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/opt/nvm/v0.11.13/bin/node" "/usr/local/opt/nvm/v0.11.13/bin/npm" "i"
npm ERR! cwd /Users/Chad/react-grid-test/node_modules/react-grid-layout
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Chad/react-grid-test/node_modules/react-grid-layout/npm-debug.log
npm ERR! not ok code 0

```

**Comment by chadobado** [comment]
Adding .git and .git/hooks and then rerunning ```npm install```

results in:

```
> react-grid-layout@0.8.2 build /Users/Chad/react-grid-test/node_modules/react-grid-layout
> bash build.sh

lib/GridItem.jsx -> build/GridItem.js
lib/ReactGridLayout.jsx -> build/ReactGridLayout.js
lib/ResponsiveReactGridLayout.jsx -> build/ResponsiveReactGridLayout.js
lib/mixins/PureDeepRenderMixin.js -> build/mixins/PureDeepRenderMixin.js
lib/mixins/WidthListeningMixin.js -> build/mixins/WidthListeningMixin.js
lib/responsiveUtils.js -> build/responsiveUtils.js
lib/utils.js -> build/utils.js
Hash: e56e04b40f2220d43f21
Version: webpack 1.8.11
Time: 96ms
                       Asset       Size  Chunks             Chunk Names
    react-grid-layout.min.js  770 bytes       0  [emitted]  react-grid-layout
react-grid-layout.min.js.map     5.4 kB       0  [emitted]  react-grid-layout
    + 3 hidden modules

ERROR in ./lib/ReactGridLayout.jsx
Module parse failed: /Users/Chad/react-grid-test/node_modules/react-grid-layout/lib/ReactGridLayout.jsx Line 102: Unexpected token (
You may need an appropriate loader to handle this file type.
|   },
| 
|   getDefaultProps() {
|     return {
|       autoSize: true,
 @ ./index-dev.js 1:17-49

ERROR in ./lib/ResponsiveReactGridLayout.jsx
Module parse failed: /Users/Chad/react-grid-test/node_modules/react-grid-layout/lib/ResponsiveReactGridLayout.jsx Line 53: Unexpected token (
You may need an appropriate loader to handle this file type.
|   },
| 
|   getDefaultProps() {
|     return {
|       breakpoints: {lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0},
 @ ./index-dev.js 2:28-70
precommit-hook@2.0.1 node_modules/precommit-hook
```

**Comment by chadobado** [comment]
Looks like the version of babel included in node_modules/.bin (5.2.2) is crashing.  The version (5.1.11) on running w/ my node (v0.11.13) appears to be working if I run it from the command line:

```babel --stage 0 --out-dir ./build ./lib```

running ```webpack``` after results in a failure (presumably due to jsx-loader?):

```
Chads-iMac:react-grid-layout Chad$ webpack
Hash: e56e04b40f2220d43f21
Version: webpack 1.8.11
Time: 94ms
                       Asset       Size  Chunks             Chunk Names
    react-grid-layout.min.js  770 bytes       0  [emitted]  react-grid-layout
react-grid-layout.min.js.map     5.4 kB       0  [emitted]  react-grid-layout
    + 3 hidden modules

ERROR in ./lib/ReactGridLayout.jsx
Module parse failed: /Users/Chad/react-grid-test/node_modules/react-grid-layout/lib/ReactGridLayout.jsx Line 102: Unexpected token (
You may need an appropriate loader to handle this file type.
|   },
| 
|   getDefaultProps() {
|     return {
|       autoSize: true,
 @ ./index-dev.js 1:17-49

ERROR in ./lib/ResponsiveReactGridLayout.jsx
Module parse failed: /Users/Chad/react-grid-test/node_modules/react-grid-layout/lib/ResponsiveReactGridLayout.jsx Line 53: Unexpected token (
You may need an appropriate loader to handle this file type.
|   },
| 
|   getDefaultProps() {
|     return {
|       breakpoints: {lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0},
 @ ./index-dev.js 2:28-70

```

**Comment by chadobado** [comment]
requiring the compiled library and running the verticalCompact example results in...

```
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of nullReactClass.createClass.Constructor @ main.js:38407ReactLegacyElementFactory.wrapCreateElement.legacyCreateElement @ main.js:15299render @ main.js:682(anonymous function) @ main.js:22209ReactPerf.measure.wrapper @ main.js:15746(anonymous function) @ main.js:21751ReactPerf.measure.wrapper @ main.js:15746ReactComponent.Mixin._mountComponentIntoNode @ main.js:20908Mixin.perform @ main.js:26312ReactComponent.Mixin.mountComponentIntoNode @ main.js:20884(anonymous function) @ main.js:1130ReactPerf.measure.wrapper @ main.js:15746ReactMount.render @ main.js:1199ReactPerf.measure.wrapper @ main.js:15746(anonymous function) @ main.js:686(anonymous function) @ main.js:690(anonymous function) @ main.js:691__webpack_require__ @ main.js:499fn @ main.js:67(anonymous function) @ main.js:530__webpack_require__ @ main.js:499(anonymous function) @ main.js:522(anonymous function) @ main.js:525
```

**Comment by STRML** [comment]
If you want to do it this way, because of the prepublish hooks, it may cause problems if you `npm install` from a git revision. I will have to try it out and see what I can do.

In any case, `verticalCompact` is in `0.8.3`.
